### ISSUE TITLE
Issue with .qmd render

### ISSUE THREAD

**Issue by Gchism94** [INFO526-DataViz/hw-01-rahulbangad98#1]
Hi Rahul,
It looks like you have a duplicate chunk name in your .qmd. Each chunk must have a unique name to render. 

```
Error in parse_block(g[-1], g[1], params.src, markdown_mode) : 
  Duplicate chunk label 'label-me-1', which has been used for the chunk:
install.packages("dsbox")
library(dsbox)
data("accidents")
accidents
```

You just need to edit this, push the changes, and then the autograder will run again.

**Comment by rahulbangad98** [comment]
hello, i fixed this issue autograder is working as expected so closing this issue
