### ISSUE TITLE
Homework 1 Feedback 

### ISSUE THREAD

**Issue by Gchism94** [INFO526-DataViz/hw-01-rahulbangad98#2]
Dear Rahul -- Below is the feedback for your assignment. Please review carefully, and stop by office hours if you have any questions about the feedback.

---

### Exercise 1: `[ 10 / 10 points]`

- Plot: `[6 / 6 points]`
- Narrative: `[4 / 4 points]`
- Feedback: Your plot is good, but I suggest another theme (e.g., `theme_minimal()`). Also, I would like to see your insight into why a density plot was used.

- [x] Resolved 
Additional feedback: you have an unnecessary `#` sign in your narrative section (`#Why`)

### Exercise 2: `[20 / 20 points]`

a. `[8 / 8 points]`

  - Histogram: `[3 / 3]`
  - Boxplot: `[3 / 3]`
  - Narrative: `[2 / 2]`
  - Feedback: I would like to see all plots in `ggplot()` so that you are able to edit them more effectively than in base plot. Its virtually impossible to do much more than you did in your base plots.  Your narrative was good overall. 

- [x] Resolved 

b. `[5 / 5 points]`

  - Boxplot: `[3 / 3]`
  - Narrative: `[2 / 2]`
  - Feedback: Good work! My minor suggestion is to capitalize the legend label and that you adjust your colors to those that represent male and female more effectively (blue and pink). This makes the boxes easier to recognize.

c. `[2 / 2 points]`

  - Feedback: Your approach is correct, but remember that colors are powerful and by removing them it actually makes the plot harder to interpret as quickly.

d. `[5 / 5 points]`

  - Time series plot: `[3 / 3]`
  - Narrative: `[2 / 2]`
  - Feedback: I agree with your approach, but the colors are not good choices. Yellow is typically a poor choice in this type of plot, and it was nearly impossible to tell that you used different shapes (which I agree with as well). 

- [x] Resolved

### Exercise 3: `[20 / 20 points]`

a. `[2/ 2]`
  - Feedback: Correct, but place answers outside of code chunks. 

b. `[2 / 2]`
  - Feedback: Correct, good work!

c. `[16 / 16]` (2 points each)
  - Feedback: Good work on the plots, but I recommend arranging them with `grid_arrange()` from the [`gridExtra`](https://www.bing.com/search?pglt=673&q=grid.arrange()&cvid=6fe9c18d58634bd7991c7f276b8cc149&aqs=edge..69i57j0j69i59j0l6j69i11004.5858j0j1&FORM=ANNAB1&PC=U531) package. 
  
### Exercise 4: `[9 / 10 points]`

- Plot: `[5 / 6 points]`
- Narrative: `[4 / 4 points]`
- Feedback: I agree with your approach, but your y-axes are cut off too short. 

- [ ] Resolved (no)

### Exercise 5: `[20 / 20 points]`

Feedback: You produced the correct plot, but your use of color makes it difficult to read. Less is more in this case. Your legends are also not in an ideal area. Lastly, the render size cuts off some labels. 

- [x] Resolved

### Overall: `[17 / 20 points]`

- `[5 / 5]` - Doesn't require reproduction: .md file is in repo, figures show up in the .md file on GitHub, no egregious errors requiring reproducing the entire analysis to be able to follow it.
- `[3 / 3]` - Code style: Line breaks after `|>` and `+`, spaces around operators, spaces after commas, lines not too long, etc.
- `[0 / 3]` - Code smell: Messy / unnecessarily complex code, difficult to follow, unaddressed warnings, etc.
 Feedback: 4/5 of your document was the readout of the accidents data. I recommend using `glimpse()` or `head()`. 

- [ ] Resolved (no)
Additional feedback: Your notebook is still 4/5 the readout from the accidents data

- `[3 / 3]` - Quality and quantity of commits: No uninformative/nonsense text in commit messages, entire assignment not committed in a single commit.
 Feedback: It is not clear what your commit messages are addressing. I suggest more frequent and specific messages. 

- [x] Resolved

- `[3 / 3]` - Reasonably sized figures.
 Feedback: There was some issues with labels being cut off. 

- [x] Resolved

- `[3 / 3]` - Font size, organization: No crazy large text for narrative, questions answered in order and identified, easy to follow.

## Late penalty

- [x] On time: No penalty
- [ ] Late, but same day (before midnight): -10 points
- [ ] Late, but next day: -20 points

**Comment by rahulbangad98** [comment]
Fixed the issue mentioned in feedback
Thanks for your feedback! The issue you pointed out has been resolved.

**Comment by Gchism94** [comment]
I have updated your scored, but there are still several sections with unresolved issues. You gained a significant number of points back and now only are missing 6.5 points out of 100.

**Comment by rahulbangad98** [comment]
Fixed the issue mentioned in feedback on the histogram and boxplot in question 2

**Comment by rahulbangad98** [comment]
closing the issue as i fixed it but regrading is still pending

**Comment by Gchism94** [comment]
You addressed several issues, but the most egregious one still remains (4/5 of the document is the readout from the accidents data). Your score is 9.6/10.
